{
 "title": "Robert",
 "time": { "from": "2026-04-24T20:31:40.734Z", "to": "2026-04-25T20:31:40.734Z" },
 "panels": [
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT MAX(last_successful) AT TIME ZONE 'Europe/Berlin' FROM server_backup LIMIT 50 "
    }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM watts\nWHERE\n  $__timeFilter(\"time\") \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") \n  and key like '%Voltage' or key like '%48_battery_volt'\nORDER BY 1"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value / 10 as \"goodwe_hv_battery_volt\",\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") \n  and key like '%hv_battery_volt'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prozent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM percentages\nWHERE\n  $__timeFilter(\"time\") \nAND SUBSTRING(key, 1, 5) != 'xmrig'\nAND SUBSTRING(key, 1, 4) != 'chia'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VoltagesDiffs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") \n    and (key like '%Cell_Diff' or key like '%diffvolt')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM temps\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max/Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") \n    and (key like '%minvolt' or key like '%maxvolt' or key like '%High_CellV' or key like '%Low_CellV')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM kilowatthours\nWHERE\n  $__timeFilter(\"time\") and key like '%Cycles'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM kilowatthours\nWHERE\n  $__timeFilter(\"time\") and key not like '%Cycles'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Xmrig Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM percentages\nWHERE\n  $__timeFilter(\"time\") \nAND SUBSTRING(key, 1, 5) = 'xmrig'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM percentages\nWHERE\n  $__timeFilter(\"time\") \nAND SUBSTRING(key, 1, 4) = 'chia'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") AND\n  key in ('Daly1_CellV_CellV_1','Daly1_CellV_CellV_2','Daly1_CellV_CellV_3','Daly1_CellV_CellV_4','Daly1_CellV_CellV_5','Daly1_CellV_CellV_6','Daly1_CellV_CellV_7','Daly1_CellV_CellV_8','Daly1_CellV_CellV_9','Daly1_CellV_CellV_10','Daly1_CellV_CellV_11','Daly1_CellV_CellV_12','Daly1_CellV_CellV_13','Daly1_CellV_CellV_14','Daly1_CellV_CellV_15','Daly1_CellV_CellV_16')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ertrag Tag",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM public.v_kwh_day"
    }
   ]
  },
  {
   "title": "Block 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") AND\n  key in ('Daly2_CellV_CellV_1','Daly2_CellV_CellV_2','Daly2_CellV_CellV_3','Daly2_CellV_CellV_4','Daly2_CellV_CellV_5','Daly2_CellV_CellV_6','Daly2_CellV_CellV_7','Daly2_CellV_CellV_8','Daly2_CellV_CellV_9','Daly2_CellV_CellV_10','Daly2_CellV_CellV_11','Daly2_CellV_CellV_12','Daly2_CellV_CellV_13','Daly2_CellV_CellV_14','Daly2_CellV_CellV_15','Daly2_CellV_CellV_16')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ertrag Monat",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM public.v_kwh_month"
    }
   ]
  },
  {
   "title": "Block 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value,\n  key\nFROM voltages\nWHERE\n  $__timeFilter(\"time\") AND\n  key in ('Daly3_CellV_CellV_1','Daly3_CellV_CellV_2','Daly3_CellV_CellV_3','Daly3_CellV_CellV_4','Daly3_CellV_CellV_5','Daly3_CellV_CellV_6','Daly3_CellV_CellV_7','Daly3_CellV_CellV_8','Daly3_CellV_CellV_9','Daly3_CellV_CellV_10','Daly3_CellV_CellV_11','Daly3_CellV_CellV_12','Daly3_CellV_CellV_13','Daly3_CellV_CellV_14','Daly3_CellV_CellV_15','Daly3_CellV_CellV_16')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ertrag Jahr",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM public.v_kwh_year"
    }
   ]
  }
 ]
}